[Tue Jul 30 15:14:27 2013] [error] [client ::1] (13)Permission denied: access to / denied
[Tue Jul 30 15:14:27 2013] [error] [client ::1] (13)Permission denied: access to /favicon.ico denied
[Tue Jul 30 15:14:35 2013] [error] [client ::1] (13)Permission denied: access to / denied
[Tue Jul 30 15:14:59 2013] [error] [client 128.171.96.206] (13)Permission denied: access to / denied
[Tue Jul 30 15:14:59 2013] [error] [client 128.171.96.206] (13)Permission denied: access to /favicon.ico denied
[Tue Jul 30 15:17:00 2013] [error] [client 128.171.96.206] (13)Permission denied: access to / denied
[Tue Jul 30 15:17:03 2013] [error] [client 128.171.96.206] (13)Permission denied: access to / denied
[Tue Jul 30 15:17:14 2013] [error] [client 128.171.96.206] (13)Permission denied: access to / denied
[Tue Jul 30 15:17:22 2013] [error] [client 128.171.96.206] (13)Permission denied: access to / denied
[Tue Jul 30 15:18:18 2013] [error] [client 128.171.96.206] (13)Permission denied: access to / denied
[Tue Jul 30 15:23:26 2013] [error] [client ::1] (13)Permission denied: access to / denied
[Tue Jul 30 15:23:27 2013] [error] [client ::1] (13)Permission denied: access to / denied
[Tue Jul 30 15:23:29 2013] [error] [client ::1] (13)Permission denied: access to / denied
[Tue Jul 30 15:23:30 2013] [error] [client ::1] (13)Permission denied: access to / denied
[Tue Jul 30 15:24:31 2013] [error] [client ::1] (13)Permission denied: access to / denied
[Tue Jul 30 15:24:32 2013] [error] [client ::1] (13)Permission denied: access to / denied
[Tue Jul 30 15:24:33 2013] [error] [client ::1] (13)Permission denied: access to / denied
[Tue Jul 30 15:24:34 2013] [error] [client ::1] (13)Permission denied: access to / denied
[Tue Jul 30 15:24:36 2013] [error] [client ::1] (13)Permission denied: access to / denied
[Tue Jul 30 15:24:57 2013] [error] [client ::1] (13)Permission denied: access to / denied
[Tue Jul 30 15:24:58 2013] [error] [client ::1] (13)Permission denied: access to / denied
[Tue Jul 30 15:27:22 2013] [notice] SELinux policy enabled; httpd running as context unconfined_u:system_r:httpd_t:s0
[Tue Jul 30 15:27:22 2013] [notice] suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
[Tue Jul 30 15:27:22 2013] [notice] Digest: generating secret for digest authentication ...
[Tue Jul 30 15:27:22 2013] [notice] Digest: done
[Tue Jul 30 15:27:22 2013] [notice] Apache/2.2.15 (Unix) DAV/2 PHP/5.3.3 mod_ssl/2.2.15 OpenSSL/1.0.0-fips mod_wsgi/3.2 Python/2.6.6 mod_perl/2.0.4 Perl/v5.10.1 configured -- resuming normal operations
[Tue Jul 30 15:27:35 2013] [error] [client ::1] (13)Permission denied: access to / denied
[Tue Jul 30 15:27:48 2013] [error] [client ::1] (13)Permission denied: access to / denied
[Tue Jul 30 15:34:31 2013] [notice] caught SIGTERM, shutting down
[Tue Jul 30 15:43:40 2013] [error] [client 128.171.96.206] (13)Permission denied: mod_wsgi (pid=5039): Unable to connect to WSGI daemon process 'application' on '/etc/httpd/logs/wsgi.5030.0.1.sock' after multiple attempts.
[Tue Jul 30 15:43:46 2013] [error] [client ::1] (13)Permission denied: mod_wsgi (pid=5040): Unable to connect to WSGI daemon process 'application' on '/etc/httpd/logs/wsgi.5030.0.1.sock' after multiple attempts.
[Tue Jul 30 15:45:28 2013] [error] [client ::1] (13)Permission denied: mod_wsgi (pid=5170): Unable to connect to WSGI daemon process 'application' on '/etc/httpd/logs/wsgi.5163.0.1.sock' after multiple attempts.
[Tue Jul 30 15:46:42 2013] [error] [client ::1] (13)Permission denied: access to / denied
[Tue Jul 30 15:51:00 2013] [error] [client ::1] (13)Permission denied: access to / denied
[Tue Jul 30 15:51:45 2013] [error] [client ::1] (13)Permission denied: access to / denied
[Tue Jul 30 15:51:47 2013] [error] [client ::1] (13)Permission denied: access to / denied
[Tue Jul 30 15:52:21 2013] [error] [client ::1] (13)Permission denied: access to / denied
[Tue Jul 30 15:52:27 2013] [error] [client 128.171.96.206] (13)Permission denied: access to / denied
[Tue Jul 30 15:53:41 2013] [error] [client ::1] (13)Permission denied: access to / denied
[Tue Jul 30 15:57:37 2013] [error] [client ::1] (13)Permission denied: access to / denied
[Tue Jul 30 16:02:06 2013] [error] [client ::1] (13)Permission denied: access to / denied
[Tue Jul 30 16:02:09 2013] [error] [client ::1] (13)Permission denied: access to / denied
[Tue Jul 30 16:03:58 2013] [error] [client ::1] (13)Permission denied: access to / denied
[Tue Jul 30 16:10:56 2013] [notice] SELinux policy enabled; httpd running as context unconfined_u:system_r:httpd_t:s0
[Tue Jul 30 16:10:56 2013] [notice] suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
[Tue Jul 30 16:10:56 2013] [notice] Digest: generating secret for digest authentication ...
[Tue Jul 30 16:10:56 2013] [notice] Digest: done
[Tue Jul 30 16:10:56 2013] [notice] Apache/2.2.15 (Unix) DAV/2 PHP/5.3.3 mod_ssl/2.2.15 OpenSSL/1.0.0-fips mod_wsgi/3.2 Python/2.6.6 mod_perl/2.0.4 Perl/v5.10.1 configured -- resuming normal operations
[Tue Jul 30 16:11:00 2013] [error] [client ::1] (13)Permission denied: mod_wsgi (pid=6283): Unable to connect to WSGI daemon process 'application' on '/etc/httpd/logs/wsgi.6276.0.1.sock' after multiple attempts.
[Tue Jul 30 16:12:32 2013] [notice] caught SIGTERM, shutting down
[Tue Jul 30 16:13:07 2013] [error] [client 128.171.96.206] (13)Permission denied: mod_wsgi (pid=6424): Unable to connect to WSGI daemon process 'application' on '/etc/httpd/logs/wsgi.6419.0.1.sock' after multiple attempts.
[Tue Jul 30 16:13:59 2013] [error] [client 128.171.96.206] (13)Permission denied: mod_wsgi (pid=6495): Unable to connect to WSGI daemon process 'application' on '/etc/httpd/logs/wsgi.6484.0.1.sock' after multiple attempts.
[Tue Jul 30 16:14:01 2013] [error] [client 128.171.96.206] (13)Permission denied: mod_wsgi (pid=6489): Unable to connect to WSGI daemon process 'application' on '/etc/httpd/logs/wsgi.6484.0.1.sock' after multiple attempts.
[Tue Jul 30 16:14:23 2013] [error] [client 128.171.96.206] (13)Permission denied: mod_wsgi (pid=6538): Unable to connect to WSGI daemon process 'application' on '/etc/httpd/logs/wsgi.6530.0.1.sock' after multiple attempts.
[Tue Jul 30 16:14:28 2013] [error] [client 128.171.96.206] (13)Permission denied: mod_wsgi (pid=6539): Unable to connect to WSGI daemon process 'application' on '/etc/httpd/logs/wsgi.6530.0.1.sock' after multiple attempts.
[Tue Jul 30 16:17:17 2013] [notice] SELinux policy enabled; httpd running as context unconfined_u:system_r:httpd_t:s0
[Tue Jul 30 16:17:17 2013] [notice] suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
[Tue Jul 30 16:17:17 2013] [notice] Digest: generating secret for digest authentication ...
[Tue Jul 30 16:17:17 2013] [notice] Digest: done
[Tue Jul 30 16:17:17 2013] [notice] Apache/2.2.15 (Unix) DAV/2 PHP/5.3.3 mod_ssl/2.2.15 OpenSSL/1.0.0-fips mod_wsgi/3.2 Python/2.6.6 mod_perl/2.0.4 Perl/v5.10.1 configured -- resuming normal operations
[Tue Jul 30 16:17:20 2013] [error] [client 128.171.96.206] (13)Permission denied: mod_wsgi (pid=6675): Unable to connect to WSGI daemon process 'application' on '/etc/httpd/logs/wsgi.6668.0.1.sock' after multiple attempts.
[Tue Jul 30 16:17:22 2013] [error] [client 128.171.96.206] (13)Permission denied: mod_wsgi (pid=6677): Unable to connect to WSGI daemon process 'application' on '/etc/httpd/logs/wsgi.6668.0.1.sock' after multiple attempts.
[Wed Jul 31 14:22:02 2013] [notice] caught SIGTERM, shutting down
[Wed Jul 31 14:22:02 2013] [notice] SELinux policy enabled; httpd running as context unconfined_u:system_r:httpd_t:s0
[Wed Jul 31 14:22:02 2013] [notice] suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
[Wed Jul 31 14:22:02 2013] [notice] Digest: generating secret for digest authentication ...
[Wed Jul 31 14:22:02 2013] [notice] Digest: done
[Wed Jul 31 14:22:02 2013] [notice] Apache/2.2.15 (Unix) DAV/2 PHP/5.3.3 mod_ssl/2.2.15 OpenSSL/1.0.0-fips mod_wsgi/3.2 Python/2.6.6 mod_perl/2.0.4 Perl/v5.10.1 configured -- resuming normal operations
[Wed Jul 31 14:22:10 2013] [error] [client 128.171.96.206] (13)Permission denied: access to / denied
[Wed Jul 31 14:22:11 2013] [error] [client 128.171.96.206] (13)Permission denied: access to / denied
[Wed Jul 31 14:22:41 2013] [error] [client 128.171.96.206] (13)Permission denied: access to / denied
[Wed Jul 31 14:22:45 2013] [error] [client 128.171.96.206] (13)Permission denied: access to / denied
[Wed Jul 31 14:22:45 2013] [error] [client 128.171.96.206] (13)Permission denied: access to /favicon.ico denied
[Wed Jul 31 14:22:45 2013] [error] [client 128.171.96.206] (13)Permission denied: access to /favicon.ico denied
[Wed Jul 31 14:22:52 2013] [error] [client 128.171.96.206] (13)Permission denied: access to /~keola denied
[Wed Jul 31 14:23:17 2013] [notice] caught SIGTERM, shutting down
[Wed Jul 31 14:23:17 2013] [notice] SELinux policy enabled; httpd running as context unconfined_u:system_r:httpd_t:s0
[Wed Jul 31 14:23:17 2013] [notice] suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
[Wed Jul 31 14:23:17 2013] [notice] Digest: generating secret for digest authentication ...
[Wed Jul 31 14:23:17 2013] [notice] Digest: done
[Wed Jul 31 14:23:17 2013] [notice] Apache/2.2.15 (Unix) DAV/2 PHP/5.3.3 mod_ssl/2.2.15 OpenSSL/1.0.0-fips mod_wsgi/3.2 Python/2.6.6 mod_perl/2.0.4 Perl/v5.10.1 configured -- resuming normal operations
[Wed Jul 31 14:23:21 2013] [error] [client 128.171.96.206] (13)Permission denied: access to /~keola denied
[Wed Jul 31 14:23:24 2013] [error] [client 128.171.96.206] (13)Permission denied: access to / denied
[Wed Jul 31 14:23:29 2013] [error] [client 128.171.96.206] (13)Permission denied: access to / denied
[Wed Jul 31 14:23:29 2013] [error] [client 128.171.96.206] (13)Permission denied: access to /favicon.ico denied
[Wed Jul 31 14:23:29 2013] [error] [client 128.171.96.206] (13)Permission denied: access to /favicon.ico denied
[Wed Jul 31 14:23:35 2013] [error] [client ::1] (13)Permission denied: access to / denied
[Wed Jul 31 14:34:40 2013] [error] [client 128.171.96.206] File does not exist: /home/keola/obsMonitor/webInterface/favicon.ico
[Wed Jul 31 14:34:44 2013] [error] [client 128.171.96.206] File does not exist: /home/keola/obsMonitor/webInterface/favicon.ico
[Wed Jul 31 14:35:57 2013] [notice] caught SIGTERM, shutting down
[Wed Jul 31 14:35:57 2013] [notice] SELinux policy enabled; httpd running as context unconfined_u:system_r:httpd_t:s0
[Wed Jul 31 14:35:57 2013] [notice] suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
[Wed Jul 31 14:35:57 2013] [notice] Digest: generating secret for digest authentication ...
[Wed Jul 31 14:35:57 2013] [notice] Digest: done
[Wed Jul 31 14:35:57 2013] [notice] Apache/2.2.15 (Unix) DAV/2 PHP/5.3.3 mod_ssl/2.2.15 OpenSSL/1.0.0-fips mod_wsgi/3.2 Python/2.6.6 mod_perl/2.0.4 Perl/v5.10.1 configured -- resuming normal operations
[Wed Jul 31 14:36:04 2013] [error] [client ::1] (13)Permission denied: mod_wsgi (pid=25702): Unable to connect to WSGI daemon process 'application' on '/etc/httpd/logs/wsgi.25697.0.1.sock' after multiple attempts.
[Wed Jul 31 14:36:04 2013] [error] [client ::1] (13)Permission denied: mod_wsgi (pid=25701): Unable to connect to WSGI daemon process 'application' on '/etc/httpd/logs/wsgi.25697.0.1.sock' after multiple attempts.
[Wed Jul 31 14:36:39 2013] [notice] caught SIGTERM, shutting down
[Wed Jul 31 14:36:39 2013] [notice] SELinux policy enabled; httpd running as context unconfined_u:system_r:httpd_t:s0
[Wed Jul 31 14:36:39 2013] [notice] suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
[Wed Jul 31 14:36:39 2013] [notice] Digest: generating secret for digest authentication ...
[Wed Jul 31 14:36:39 2013] [notice] Digest: done
[Wed Jul 31 14:36:39 2013] [notice] Apache/2.2.15 (Unix) DAV/2 PHP/5.3.3 mod_ssl/2.2.15 OpenSSL/1.0.0-fips mod_wsgi/3.2 Python/2.6.6 mod_perl/2.0.4 Perl/v5.10.1 configured -- resuming normal operations
[Wed Jul 31 14:36:43 2013] [error] [client ::1] (13)Permission denied: mod_wsgi (pid=25808): Unable to connect to WSGI daemon process 'application' on '/etc/httpd/logs/wsgi.25799.0.1.sock' after multiple attempts.
[Wed Jul 31 14:36:45 2013] [error] [client ::1] (13)Permission denied: mod_wsgi (pid=25805): Unable to connect to WSGI daemon process 'application' on '/etc/httpd/logs/wsgi.25799.0.1.sock' after multiple attempts.
[Wed Jul 31 14:39:47 2013] [notice] caught SIGTERM, shutting down
[Wed Jul 31 14:39:47 2013] [notice] SELinux policy enabled; httpd running as context unconfined_u:system_r:httpd_t:s0
[Wed Jul 31 14:39:47 2013] [notice] suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
[Wed Jul 31 14:39:47 2013] [notice] Digest: generating secret for digest authentication ...
[Wed Jul 31 14:39:47 2013] [notice] Digest: done
[Wed Jul 31 14:39:47 2013] [notice] Apache/2.2.15 (Unix) DAV/2 PHP/5.3.3 mod_ssl/2.2.15 OpenSSL/1.0.0-fips mod_wsgi/3.2 Python/2.6.6 mod_perl/2.0.4 Perl/v5.10.1 configured -- resuming normal operations
[Wed Jul 31 16:41:15 2013] [notice] caught SIGTERM, shutting down
[Wed Jul 31 16:41:16 2013] [notice] SELinux policy enabled; httpd running as context unconfined_u:system_r:httpd_t:s0
[Wed Jul 31 16:41:16 2013] [notice] suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
[Wed Jul 31 16:41:16 2013] [notice] Digest: generating secret for digest authentication ...
[Wed Jul 31 16:41:16 2013] [notice] Digest: done
[Wed Jul 31 16:41:16 2013] [notice] Apache/2.2.15 (Unix) DAV/2 PHP/5.3.3 mod_ssl/2.2.15 OpenSSL/1.0.0-fips mod_wsgi/3.2 Python/2.6.6 mod_perl/2.0.4 Perl/v5.10.1 configured -- resuming normal operations
[Wed Jul 31 16:43:28 2013] [notice] caught SIGTERM, shutting down
[Wed Jul 31 16:43:28 2013] [notice] SELinux policy enabled; httpd running as context unconfined_u:system_r:httpd_t:s0
[Wed Jul 31 16:43:28 2013] [notice] suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
[Wed Jul 31 16:43:28 2013] [notice] Digest: generating secret for digest authentication ...
[Wed Jul 31 16:43:28 2013] [notice] Digest: done
[Wed Jul 31 16:43:28 2013] [notice] Apache/2.2.15 (Unix) DAV/2 PHP/5.3.3 mod_ssl/2.2.15 OpenSSL/1.0.0-fips mod_wsgi/3.2 Python/2.6.6 mod_perl/2.0.4 Perl/v5.10.1 configured -- resuming normal operations
[Wed Jul 31 16:45:14 2013] [notice] caught SIGTERM, shutting down
[Wed Jul 31 16:45:14 2013] [notice] SELinux policy enabled; httpd running as context unconfined_u:system_r:httpd_t:s0
[Wed Jul 31 16:45:14 2013] [notice] suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
[Wed Jul 31 16:45:14 2013] [notice] Digest: generating secret for digest authentication ...
[Wed Jul 31 16:45:14 2013] [notice] Digest: done
[Wed Jul 31 16:45:14 2013] [notice] Apache/2.2.15 (Unix) DAV/2 PHP/5.3.3 mod_ssl/2.2.15 OpenSSL/1.0.0-fips mod_wsgi/3.2 Python/2.6.6 mod_perl/2.0.4 Perl/v5.10.1 configured -- resuming normal operations
[Wed Jul 31 16:45:29 2013] [notice] caught SIGTERM, shutting down
[Wed Jul 31 16:45:29 2013] [notice] SELinux policy enabled; httpd running as context unconfined_u:system_r:httpd_t:s0
[Wed Jul 31 16:45:29 2013] [notice] suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
[Wed Jul 31 16:45:29 2013] [notice] Digest: generating secret for digest authentication ...
[Wed Jul 31 16:45:29 2013] [notice] Digest: done
[Wed Jul 31 16:45:29 2013] [notice] Apache/2.2.15 (Unix) DAV/2 PHP/5.3.3 mod_ssl/2.2.15 OpenSSL/1.0.0-fips mod_wsgi/3.2 Python/2.6.6 mod_perl/2.0.4 Perl/v5.10.1 configured -- resuming normal operations
[Wed Jul 31 16:49:14 2013] [notice] caught SIGTERM, shutting down
[Wed Jul 31 16:49:14 2013] [notice] SELinux policy enabled; httpd running as context unconfined_u:system_r:httpd_t:s0
[Wed Jul 31 16:49:14 2013] [notice] suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
[Wed Jul 31 16:49:14 2013] [notice] Digest: generating secret for digest authentication ...
[Wed Jul 31 16:49:14 2013] [notice] Digest: done
[Wed Jul 31 16:49:14 2013] [notice] Apache/2.2.15 (Unix) DAV/2 PHP/5.3.3 mod_ssl/2.2.15 OpenSSL/1.0.0-fips mod_wsgi/3.2 Python/2.6.6 mod_perl/2.0.4 Perl/v5.10.1 configured -- resuming normal operations
[Wed Jul 31 17:03:52 2013] [notice] caught SIGTERM, shutting down
[Wed Jul 31 17:03:52 2013] [notice] SELinux policy enabled; httpd running as context unconfined_u:system_r:httpd_t:s0
[Wed Jul 31 17:03:52 2013] [notice] suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
[Wed Jul 31 17:03:52 2013] [notice] Digest: generating secret for digest authentication ...
[Wed Jul 31 17:03:52 2013] [notice] Digest: done
[Wed Jul 31 17:03:52 2013] [notice] Apache/2.2.15 (Unix) DAV/2 PHP/5.3.3 mod_ssl/2.2.15 OpenSSL/1.0.0-fips mod_wsgi/3.2 Python/2.6.6 mod_perl/2.0.4 Perl/v5.10.1 configured -- resuming normal operations
[Wed Jul 31 17:06:26 2013] [notice] caught SIGTERM, shutting down
[Wed Jul 31 17:06:26 2013] [notice] SELinux policy enabled; httpd running as context unconfined_u:system_r:httpd_t:s0
[Wed Jul 31 17:06:26 2013] [notice] suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
[Wed Jul 31 17:06:26 2013] [notice] Digest: generating secret for digest authentication ...
[Wed Jul 31 17:06:26 2013] [notice] Digest: done
[Wed Jul 31 17:06:27 2013] [notice] Apache/2.2.15 (Unix) DAV/2 PHP/5.3.3 mod_ssl/2.2.15 OpenSSL/1.0.0-fips mod_wsgi/3.2 Python/2.6.6 mod_perl/2.0.4 Perl/v5.10.1 configured -- resuming normal operations
[Wed Jul 31 17:06:47 2013] [notice] caught SIGTERM, shutting down
[Wed Jul 31 17:06:47 2013] [notice] SELinux policy enabled; httpd running as context unconfined_u:system_r:httpd_t:s0
[Wed Jul 31 17:06:47 2013] [notice] suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
[Wed Jul 31 17:06:47 2013] [notice] Digest: generating secret for digest authentication ...
[Wed Jul 31 17:06:47 2013] [notice] Digest: done
[Wed Jul 31 17:06:47 2013] [notice] Apache/2.2.15 (Unix) DAV/2 PHP/5.3.3 mod_ssl/2.2.15 OpenSSL/1.0.0-fips mod_wsgi/3.2 Python/2.6.6 mod_perl/2.0.4 Perl/v5.10.1 configured -- resuming normal operations
[Wed Jul 31 17:07:26 2013] [notice] caught SIGTERM, shutting down
[Wed Jul 31 17:07:26 2013] [notice] SELinux policy enabled; httpd running as context unconfined_u:system_r:httpd_t:s0
[Wed Jul 31 17:07:26 2013] [notice] suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
[Wed Jul 31 17:07:26 2013] [notice] Digest: generating secret for digest authentication ...
[Wed Jul 31 17:07:26 2013] [notice] Digest: done
[Wed Jul 31 17:07:26 2013] [notice] Apache/2.2.15 (Unix) DAV/2 PHP/5.3.3 mod_ssl/2.2.15 OpenSSL/1.0.0-fips mod_wsgi/3.2 Python/2.6.6 mod_perl/2.0.4 Perl/v5.10.1 configured -- resuming normal operations
[Wed Jul 31 17:08:27 2013] [notice] caught SIGTERM, shutting down
[Wed Jul 31 17:08:27 2013] [notice] SELinux policy enabled; httpd running as context unconfined_u:system_r:httpd_t:s0
[Wed Jul 31 17:08:27 2013] [notice] suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
[Wed Jul 31 17:08:27 2013] [notice] Digest: generating secret for digest authentication ...
[Wed Jul 31 17:08:27 2013] [notice] Digest: done
[Wed Jul 31 17:08:27 2013] [notice] Apache/2.2.15 (Unix) DAV/2 PHP/5.3.3 mod_ssl/2.2.15 OpenSSL/1.0.0-fips mod_wsgi/3.2 Python/2.6.6 mod_perl/2.0.4 Perl/v5.10.1 configured -- resuming normal operations
[Wed Jul 31 17:09:34 2013] [notice] caught SIGTERM, shutting down
[Wed Jul 31 17:09:45 2013] [notice] SELinux policy enabled; httpd running as context unconfined_u:system_r:httpd_t:s0
[Wed Jul 31 17:09:45 2013] [notice] suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
[Wed Jul 31 17:09:45 2013] [notice] Digest: generating secret for digest authentication ...
[Wed Jul 31 17:09:45 2013] [notice] Digest: done
[Wed Jul 31 17:09:45 2013] [notice] Apache/2.2.15 (Unix) DAV/2 PHP/5.3.3 mod_ssl/2.2.15 OpenSSL/1.0.0-fips mod_wsgi/3.2 Python/2.6.6 mod_perl/2.0.4 Perl/v5.10.1 configured -- resuming normal operations
[Wed Jul 31 17:09:47 2013] [notice] caught SIGTERM, shutting down
[Wed Jul 31 17:09:47 2013] [notice] SELinux policy enabled; httpd running as context unconfined_u:system_r:httpd_t:s0
[Wed Jul 31 17:09:47 2013] [notice] suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
[Wed Jul 31 17:09:47 2013] [notice] Digest: generating secret for digest authentication ...
[Wed Jul 31 17:09:47 2013] [notice] Digest: done
[Wed Jul 31 17:09:47 2013] [notice] Apache/2.2.15 (Unix) DAV/2 PHP/5.3.3 mod_ssl/2.2.15 OpenSSL/1.0.0-fips mod_wsgi/3.2 Python/2.6.6 mod_perl/2.0.4 Perl/v5.10.1 configured -- resuming normal operations
[Wed Jul 31 17:10:09 2013] [error] [client 128.171.96.206] File does not exist: /home/keola/public_html/favicon.ico
[Wed Jul 31 17:10:09 2013] [error] [client 128.171.96.206] File does not exist: /home/keola/public_html/favicon.ico
[Wed Jul 31 19:01:47 2013] [notice] caught SIGTERM, shutting down
[Wed Jul 31 19:01:48 2013] [notice] SELinux policy enabled; httpd running as context unconfined_u:system_r:httpd_t:s0
[Wed Jul 31 19:01:48 2013] [notice] suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
[Wed Jul 31 19:01:48 2013] [notice] Digest: generating secret for digest authentication ...
[Wed Jul 31 19:01:48 2013] [notice] Digest: done
[Wed Jul 31 19:01:48 2013] [notice] Apache/2.2.15 (Unix) DAV/2 PHP/5.3.3 mod_ssl/2.2.15 OpenSSL/1.0.0-fips mod_wsgi/3.2 Python/2.6.6 mod_perl/2.0.4 Perl/v5.10.1 configured -- resuming normal operations
[Wed Jul 31 19:02:04 2013] [error] [client 128.171.96.206] PHP Deprecated:  moadminModel::_mongo(): The Mongo class is deprecated, please use the MongoClient class in /home/keola/public_html/moadmin.php on line 297
[Wed Jul 31 19:02:06 2013] [error] [client 128.171.96.206] File does not exist: /home/keola/public_html/favicon.ico
[Wed Jul 31 19:03:27 2013] [error] [client 128.171.96.206] PHP Deprecated:  moadminModel::_mongo(): The Mongo class is deprecated, please use the MongoClient class in /home/keola/public_html/moadmin.php on line 297, referer: http://observinglogs:5000/moadmin.php
[Wed Jul 31 19:03:40 2013] [error] [client 128.171.96.206] PHP Deprecated:  moadminModel::_mongo(): The Mongo class is deprecated, please use the MongoClient class in /home/keola/public_html/moadmin.php on line 297, referer: http://observinglogs:5000/moadmin.php
[Wed Jul 31 19:03:49 2013] [error] [client 128.171.96.206] PHP Deprecated:  moadminModel::_mongo(): The Mongo class is deprecated, please use the MongoClient class in /home/keola/public_html/moadmin.php on line 297, referer: http://observinglogs:5000/moadmin.php?db=obsLog&newdb=
[Wed Jul 31 19:05:26 2013] [error] [client 128.171.96.206] PHP Deprecated:  moadminModel::_mongo(): The Mongo class is deprecated, please use the MongoClient class in /home/keola/public_html/moadmin.php on line 297, referer: http://observinglogs:5000/moadmin.php?db=obsLog&action=listRows&collection=activeLogs
[Wed Jul 31 19:06:35 2013] [error] [client 128.171.96.206] PHP Deprecated:  moadminModel::_mongo(): The Mongo class is deprecated, please use the MongoClient class in /home/keola/public_html/moadmin.php on line 297, referer: http://observinglogs:5000/moadmin.php?db=obsLog&action=listRows&collection=fits
[Wed Jul 31 19:07:01 2013] [error] [client 128.171.96.206] PHP Deprecated:  moadminModel::_mongo(): The Mongo class is deprecated, please use the MongoClient class in /home/keola/public_html/moadmin.php on line 297, referer: http://observinglogs:5000/moadmin.php?db=obsLog&action=listRows&collection=instruments
[Wed Jul 31 19:07:05 2013] [error] [client 128.171.96.206] PHP Deprecated:  moadminModel::_mongo(): The Mongo class is deprecated, please use the MongoClient class in /home/keola/public_html/moadmin.php on line 297, referer: http://observinglogs:5000/moadmin.php?db=obsLog&action=listRows&collection=fits
[Wed Jul 31 19:07:06 2013] [error] [client 128.171.96.206] PHP Deprecated:  moadminModel::_mongo(): The Mongo class is deprecated, please use the MongoClient class in /home/keola/public_html/moadmin.php on line 297, referer: http://observinglogs:5000/moadmin.php?db=obsLog&action=listRows&collection=activeLogs
[Wed Jul 31 19:07:07 2013] [error] [client 128.171.96.206] PHP Deprecated:  moadminModel::_mongo(): The Mongo class is deprecated, please use the MongoClient class in /home/keola/public_html/moadmin.php on line 297, referer: http://observinglogs:5000/moadmin.php?db=obsLog&newdb=
[Wed Jul 31 19:07:08 2013] [error] [client 128.171.96.206] PHP Deprecated:  moadminModel::_mongo(): The Mongo class is deprecated, please use the MongoClient class in /home/keola/public_html/moadmin.php on line 297, referer: http://observinglogs:5000/moadmin.php
[Wed Jul 31 19:07:12 2013] [error] [client 128.171.96.206] PHP Deprecated:  moadminModel::_mongo(): The Mongo class is deprecated, please use the MongoClient class in /home/keola/public_html/moadmin.php on line 297
[Wed Jul 31 19:07:28 2013] [error] [client 128.171.96.206] PHP Deprecated:  moadminModel::_mongo(): The Mongo class is deprecated, please use the MongoClient class in /home/keola/public_html/moadmin.php on line 297, referer: http://observinglogs:5000/moadmin.php
[Wed Jul 31 19:07:30 2013] [error] [client 128.171.96.206] PHP Deprecated:  moadminModel::_mongo(): The Mongo class is deprecated, please use the MongoClient class in /home/keola/public_html/moadmin.php on line 297, referer: http://observinglogs:5000/moadmin.php?db=local&newdb=
[Wed Jul 31 19:07:46 2013] [error] [client 128.171.96.206] PHP Deprecated:  moadminModel::_mongo(): The Mongo class is deprecated, please use the MongoClient class in /home/keola/public_html/moadmin.php on line 297, referer: http://observinglogs:5000/moadmin.php?db=local&action=listRows&collection=startup_log
[Wed Jul 31 20:28:17 2013] [error] [client ::1] File does not exist: /home/keola/public_html/favicon.ico
[Wed Jul 31 23:56:12 2013] [error] ERROR:server:Exception on /fits/51f9b2ec52ddfd690fcb73a8/51f9b2d952ddfd68f95bb489 [GET]
[Wed Jul 31 23:56:12 2013] [error] Traceback (most recent call last):
[Wed Jul 31 23:56:12 2013] [error]   File "/usr/lib/python2.6/site-packages/Flask-0.10.1-py2.6.egg/flask/app.py", line 1817, in wsgi_app
[Wed Jul 31 23:56:12 2013] [error]     response = self.full_dispatch_request()
[Wed Jul 31 23:56:12 2013] [error]   File "/usr/lib/python2.6/site-packages/Flask-0.10.1-py2.6.egg/flask/app.py", line 1477, in full_dispatch_request
[Wed Jul 31 23:56:12 2013] [error]     rv = self.handle_user_exception(e)
[Wed Jul 31 23:56:12 2013] [error]   File "/usr/lib/python2.6/site-packages/Flask-0.10.1-py2.6.egg/flask/app.py", line 1381, in handle_user_exception
[Wed Jul 31 23:56:12 2013] [error]     reraise(exc_type, exc_value, tb)
[Wed Jul 31 23:56:12 2013] [error]   File "/usr/lib/python2.6/site-packages/Flask-0.10.1-py2.6.egg/flask/app.py", line 1475, in full_dispatch_request
[Wed Jul 31 23:56:12 2013] [error]     rv = self.dispatch_request()
[Wed Jul 31 23:56:12 2013] [error]   File "/usr/lib/python2.6/site-packages/Flask-0.10.1-py2.6.egg/flask/app.py", line 1461, in dispatch_request
[Wed Jul 31 23:56:12 2013] [error]     return self.view_functions[rule.endpoint](**req.view_args)
[Wed Jul 31 23:56:12 2013] [error]   File "/home/keola/obsMonitor/webInterface/server.py", line 223, in list_fits
[Wed Jul 31 23:56:12 2013] [error]     fitsView = db.fitsViews.find_one({"_id": ObjectId( viewID ) })
[Wed Jul 31 23:56:12 2013] [error]   File "/usr/lib/python2.6/site-packages/pymongo-2.5.2-py2.6-linux-x86_64.egg/pymongo/collection.py", line 596, in find_one
[Wed Jul 31 23:56:12 2013] [error]     for result in self.find(spec_or_id, *args, **kwargs).limit(-1):
[Wed Jul 31 23:56:12 2013] [error]   File "/usr/lib/python2.6/site-packages/pymongo-2.5.2-py2.6-linux-x86_64.egg/pymongo/cursor.py", line 814, in next
[Wed Jul 31 23:56:12 2013] [error]     if len(self.__data) or self._refresh():
[Wed Jul 31 23:56:12 2013] [error]   File "/usr/lib/python2.6/site-packages/pymongo-2.5.2-py2.6-linux-x86_64.egg/pymongo/cursor.py", line 763, in _refresh
[Wed Jul 31 23:56:12 2013] [error]     self.__uuid_subtype))
[Wed Jul 31 23:56:12 2013] [error]   File "/usr/lib/python2.6/site-packages/pymongo-2.5.2-py2.6-linux-x86_64.egg/pymongo/cursor.py", line 720, in __send_message
[Wed Jul 31 23:56:12 2013] [error]     self.__uuid_subtype)
[Wed Jul 31 23:56:12 2013] [error]   File "/usr/lib/python2.6/site-packages/pymongo-2.5.2-py2.6-linux-x86_64.egg/pymongo/helpers.py", line 100, in _unpack_response
[Wed Jul 31 23:56:12 2013] [error]     error_object["$err"])
[Wed Jul 31 23:56:12 2013] [error] OperationFailure: database error: not authorized for query on obsLog.fitsViews
[Wed Jul 31 23:56:12 2013] [error] ERROR:server:Exception on /fits/51f9b2ec52ddfd690fcb73a8/51f9b2d952ddfd68f95bb489 [GET]
[Wed Jul 31 23:56:12 2013] [error] Traceback (most recent call last):
[Wed Jul 31 23:56:12 2013] [error]   File "/usr/lib/python2.6/site-packages/Flask-0.10.1-py2.6.egg/flask/app.py", line 1817, in wsgi_app
[Wed Jul 31 23:56:12 2013] [error]     response = self.full_dispatch_request()
[Wed Jul 31 23:56:12 2013] [error]   File "/usr/lib/python2.6/site-packages/Flask-0.10.1-py2.6.egg/flask/app.py", line 1477, in full_dispatch_request
[Wed Jul 31 23:56:12 2013] [error]     rv = self.handle_user_exception(e)
[Wed Jul 31 23:56:12 2013] [error]   File "/usr/lib/python2.6/site-packages/Flask-0.10.1-py2.6.egg/flask/app.py", line 1381, in handle_user_exception
[Wed Jul 31 23:56:12 2013] [error]     reraise(exc_type, exc_value, tb)
[Wed Jul 31 23:56:12 2013] [error]   File "/usr/lib/python2.6/site-packages/Flask-0.10.1-py2.6.egg/flask/app.py", line 1475, in full_dispatch_request
[Wed Jul 31 23:56:12 2013] [error]     rv = self.dispatch_request()
[Wed Jul 31 23:56:12 2013] [error]   File "/usr/lib/python2.6/site-packages/Flask-0.10.1-py2.6.egg/flask/app.py", line 1461, in dispatch_request
[Wed Jul 31 23:56:12 2013] [error]     return self.view_functions[rule.endpoint](**req.view_args)
[Wed Jul 31 23:56:12 2013] [error]   File "/home/keola/obsMonitor/webInterface/server.py", line 223, in list_fits
[Wed Jul 31 23:56:12 2013] [error]     fitsView = db.fitsViews.find_one({"_id": ObjectId( viewID ) })
[Wed Jul 31 23:56:12 2013] [error]   File "/usr/lib/python2.6/site-packages/pymongo-2.5.2-py2.6-linux-x86_64.egg/pymongo/collection.py", line 596, in find_one
[Wed Jul 31 23:56:12 2013] [error]     for result in self.find(spec_or_id, *args, **kwargs).limit(-1):
[Wed Jul 31 23:56:12 2013] [error]   File "/usr/lib/python2.6/site-packages/pymongo-2.5.2-py2.6-linux-x86_64.egg/pymongo/cursor.py", line 814, in next
[Wed Jul 31 23:56:12 2013] [error]     if len(self.__data) or self._refresh():
[Wed Jul 31 23:56:12 2013] [error]   File "/usr/lib/python2.6/site-packages/pymongo-2.5.2-py2.6-linux-x86_64.egg/pymongo/cursor.py", line 763, in _refresh
[Wed Jul 31 23:56:12 2013] [error]     self.__uuid_subtype))
[Wed Jul 31 23:56:12 2013] [error]   File "/usr/lib/python2.6/site-packages/pymongo-2.5.2-py2.6-linux-x86_64.egg/pymongo/cursor.py", line 720, in __send_message
[Wed Jul 31 23:56:12 2013] [error]     self.__uuid_subtype)
[Wed Jul 31 23:56:12 2013] [error]   File "/usr/lib/python2.6/site-packages/pymongo-2.5.2-py2.6-linux-x86_64.egg/pymongo/helpers.py", line 100, in _unpack_response
[Wed Jul 31 23:56:12 2013] [error]     error_object["$err"])
[Wed Jul 31 23:56:12 2013] [error] OperationFailure: database error: not authorized for query on obsLog.fitsViews
[Wed Jul 31 23:56:12 2013] [error] ERROR:server:Exception on /fits/51f9b2ec52ddfd690fcb73a8/51f9b2d952ddfd68f95bb489 [GET]
[Wed Jul 31 23:56:12 2013] [error] Traceback (most recent call last):
[Wed Jul 31 23:56:12 2013] [error]   File "/usr/lib/python2.6/site-packages/Flask-0.10.1-py2.6.egg/flask/app.py", line 1817, in wsgi_app
[Wed Jul 31 23:56:12 2013] [error]     response = self.full_dispatch_request()
[Wed Jul 31 23:56:12 2013] [error]   File "/usr/lib/python2.6/site-packages/Flask-0.10.1-py2.6.egg/flask/app.py", line 1477, in full_dispatch_request
[Wed Jul 31 23:56:12 2013] [error]     rv = self.handle_user_exception(e)
[Wed Jul 31 23:56:12 2013] [error]   File "/usr/lib/python2.6/site-packages/Flask-0.10.1-py2.6.egg/flask/app.py", line 1381, in handle_user_exception
[Wed Jul 31 23:56:12 2013] [error]     reraise(exc_type, exc_value, tb)
[Wed Jul 31 23:56:12 2013] [error]   File "/usr/lib/python2.6/site-packages/Flask-0.10.1-py2.6.egg/flask/app.py", line 1475, in full_dispatch_request
[Wed Jul 31 23:56:12 2013] [error]     rv = self.dispatch_request()
[Wed Jul 31 23:56:12 2013] [error]   File "/usr/lib/python2.6/site-packages/Flask-0.10.1-py2.6.egg/flask/app.py", line 1461, in dispatch_request
[Wed Jul 31 23:56:12 2013] [error]     return self.view_functions[rule.endpoint](**req.view_args)
[Wed Jul 31 23:56:12 2013] [error]   File "/home/keola/obsMonitor/webInterface/server.py", line 223, in list_fits
[Wed Jul 31 23:56:12 2013] [error]     fitsView = db.fitsViews.find_one({"_id": ObjectId( viewID ) })
[Wed Jul 31 23:56:12 2013] [error]   File "/usr/lib/python2.6/site-packages/pymongo-2.5.2-py2.6-linux-x86_64.egg/pymongo/collection.py", line 596, in find_one
[Wed Jul 31 23:56:12 2013] [error]     for result in self.find(spec_or_id, *args, **kwargs).limit(-1):
[Wed Jul 31 23:56:12 2013] [error]   File "/usr/lib/python2.6/site-packages/pymongo-2.5.2-py2.6-linux-x86_64.egg/pymongo/cursor.py", line 814, in next
[Wed Jul 31 23:56:12 2013] [error]     if len(self.__data) or self._refresh():
[Wed Jul 31 23:56:12 2013] [error]   File "/usr/lib/python2.6/site-packages/pymongo-2.5.2-py2.6-linux-x86_64.egg/pymongo/cursor.py", line 763, in _refresh
[Wed Jul 31 23:56:12 2013] [error]     self.__uuid_subtype))
[Wed Jul 31 23:56:12 2013] [error]   File "/usr/lib/python2.6/site-packages/pymongo-2.5.2-py2.6-linux-x86_64.egg/pymongo/cursor.py", line 720, in __send_message
[Wed Jul 31 23:56:12 2013] [error]     self.__uuid_subtype)
[Wed Jul 31 23:56:12 2013] [error]   File "/usr/lib/python2.6/site-packages/pymongo-2.5.2-py2.6-linux-x86_64.egg/pymongo/helpers.py", line 100, in _unpack_response
[Wed Jul 31 23:56:12 2013] [error]     error_object["$err"])
[Wed Jul 31 23:56:12 2013] [error] OperationFailure: database error: not authorized for query on obsLog.fitsViews
[Wed Jul 31 23:56:12 2013] [error] ERROR:server:Exception on /fits/51f9b2ec52ddfd690fcb73a8/51f9b2d952ddfd68f95bb489 [GET]
[Wed Jul 31 23:56:12 2013] [error] Traceback (most recent call last):
[Wed Jul 31 23:56:12 2013] [error]   File "/usr/lib/python2.6/site-packages/Flask-0.10.1-py2.6.egg/flask/app.py", line 1817, in wsgi_app
[Wed Jul 31 23:56:12 2013] [error]     response = self.full_dispatch_request()
[Wed Jul 31 23:56:12 2013] [error]   File "/usr/lib/python2.6/site-packages/Flask-0.10.1-py2.6.egg/flask/app.py", line 1477, in full_dispatch_request
[Wed Jul 31 23:56:12 2013] [error]     rv = self.handle_user_exception(e)
[Wed Jul 31 23:56:12 2013] [error]   File "/usr/lib/python2.6/site-packages/Flask-0.10.1-py2.6.egg/flask/app.py", line 1381, in handle_user_exception
[Wed Jul 31 23:56:12 2013] [error]     reraise(exc_type, exc_value, tb)
[Wed Jul 31 23:56:12 2013] [error]   File "/usr/lib/python2.6/site-packages/Flask-0.10.1-py2.6.egg/flask/app.py", line 1475, in full_dispatch_request
[Wed Jul 31 23:56:12 2013] [error]     rv = self.dispatch_request()
[Wed Jul 31 23:56:12 2013] [error]   File "/usr/lib/python2.6/site-packages/Flask-0.10.1-py2.6.egg/flask/app.py", line 1461, in dispatch_request
[Wed Jul 31 23:56:12 2013] [error]     return self.view_functions[rule.endpoint](**req.view_args)
[Wed Jul 31 23:56:12 2013] [error]   File "/home/keola/obsMonitor/webInterface/server.py", line 223, in list_fits
[Wed Jul 31 23:56:12 2013] [error]     fitsView = db.fitsViews.find_one({"_id": ObjectId( viewID ) })
[Wed Jul 31 23:56:12 2013] [error]   File "/usr/lib/python2.6/site-packages/pymongo-2.5.2-py2.6-linux-x86_64.egg/pymongo/collection.py", line 596, in find_one
[Wed Jul 31 23:56:12 2013] [error]     for result in self.find(spec_or_id, *args, **kwargs).limit(-1):
[Wed Jul 31 23:56:12 2013] [error]   File "/usr/lib/python2.6/site-packages/pymongo-2.5.2-py2.6-linux-x86_64.egg/pymongo/cursor.py", line 814, in next
[Wed Jul 31 23:56:12 2013] [error]     if len(self.__data) or self._refresh():
[Wed Jul 31 23:56:12 2013] [error]   File "/usr/lib/python2.6/site-packages/pymongo-2.5.2-py2.6-linux-x86_64.egg/pymongo/cursor.py", line 763, in _refresh
[Wed Jul 31 23:56:12 2013] [error]     self.__uuid_subtype))
[Wed Jul 31 23:56:12 2013] [error]   File "/usr/lib/python2.6/site-packages/pymongo-2.5.2-py2.6-linux-x86_64.egg/pymongo/cursor.py", line 720, in __send_message
[Wed Jul 31 23:56:12 2013] [error]     self.__uuid_subtype)
[Wed Jul 31 23:56:12 2013] [error]   File "/usr/lib/python2.6/site-packages/pymongo-2.5.2-py2.6-linux-x86_64.egg/pymongo/helpers.py", line 100, in _unpack_response
[Wed Jul 31 23:56:12 2013] [error]     error_object["$err"])
[Wed Jul 31 23:56:12 2013] [error] OperationFailure: database error: not authorized for query on obsLog.fitsViews
[Wed Jul 31 23:56:12 2013] [error] ERROR:server:Exception on /fits/51f9b2ec52ddfd690fcb73a8/51f9b2d952ddfd68f95bb489 [GET]
[Wed Jul 31 23:56:12 2013] [error] Traceback (most recent call last):
[Wed Jul 31 23:56:12 2013] [error]   File "/usr/lib/python2.6/site-packages/Flask-0.10.1-py2.6.egg/flask/app.py", line 1817, in wsgi_app
[Wed Jul 31 23:56:12 2013] [error]     response = self.full_dispatch_request()
[Wed Jul 31 23:56:12 2013] [error]   File "/usr/lib/python2.6/site-packages/Flask-0.10.1-py2.6.egg/flask/app.py", line 1477, in full_dispatch_request
[Wed Jul 31 23:56:12 2013] [error]     rv = self.handle_user_exception(e)
[Wed Jul 31 23:56:12 2013] [error]   File "/usr/lib/python2.6/site-packages/Flask-0.10.1-py2.6.egg/flask/app.py", line 1381, in handle_user_exception
[Wed Jul 31 23:56:12 2013] [error]     reraise(exc_type, exc_value, tb)
[Wed Jul 31 23:56:12 2013] [error]   File "/usr/lib/python2.6/site-packages/Flask-0.10.1-py2.6.egg/flask/app.py", line 1475, in full_dispatch_request
[Wed Jul 31 23:56:12 2013] [error]     rv = self.dispatch_request()
[Wed Jul 31 23:56:12 2013] [error]   File "/usr/lib/python2.6/site-packages/Flask-0.10.1-py2.6.egg/flask/app.py", line 1461, in dispatch_request
[Wed Jul 31 23:56:12 2013] [error]     return self.view_functions[rule.endpoint](**req.view_args)
[Wed Jul 31 23:56:12 2013] [error]   File "/home/keola/obsMonitor/webInterface/server.py", line 223, in list_fits
[Wed Jul 31 23:56:12 2013] [error]     fitsView = db.fitsViews.find_one({"_id": ObjectId( viewID ) })
[Wed Jul 31 23:56:12 2013] [error]   File "/usr/lib/python2.6/site-packages/pymongo-2.5.2-py2.6-linux-x86_64.egg/pymongo/collection.py", line 596, in find_one
[Wed Jul 31 23:56:12 2013] [error]     for result in self.find(spec_or_id, *args, **kwargs).limit(-1):
[Wed Jul 31 23:56:12 2013] [error]   File "/usr/lib/python2.6/site-packages/pymongo-2.5.2-py2.6-linux-x86_64.egg/pymongo/cursor.py", line 814, in next
[Wed Jul 31 23:56:12 2013] [error]     if len(self.__data) or self._refresh():
[Wed Jul 31 23:56:12 2013] [error]   File "/usr/lib/python2.6/site-packages/pymongo-2.5.2-py2.6-linux-x86_64.egg/pymongo/cursor.py", line 763, in _refresh
[Wed Jul 31 23:56:12 2013] [error]     self.__uuid_subtype))
[Wed Jul 31 23:56:12 2013] [error]   File "/usr/lib/python2.6/site-packages/pymongo-2.5.2-py2.6-linux-x86_64.egg/pymongo/cursor.py", line 720, in __send_message
[Wed Jul 31 23:56:12 2013] [error]     self.__uuid_subtype)
[Wed Jul 31 23:56:12 2013] [error]   File "/usr/lib/python2.6/site-packages/pymongo-2.5.2-py2.6-linux-x86_64.egg/pymongo/helpers.py", line 100, in _unpack_response
[Wed Jul 31 23:56:12 2013] [error]     error_object["$err"])
[Wed Jul 31 23:56:12 2013] [error] OperationFailure: database error: not authorized for query on obsLog.fitsViews
[Thu Aug 01 15:15:55 2013] [error] ERROR:server:Exception on /fits/51f9b2ec52ddfd690fcb73a8/51f9b2d952ddfd68f95bb489 [GET]
[Thu Aug 01 15:15:55 2013] [error] Traceback (most recent call last):
[Thu Aug 01 15:15:55 2013] [error]   File "/usr/lib/python2.6/site-packages/Flask-0.10.1-py2.6.egg/flask/app.py", line 1817, in wsgi_app
[Thu Aug 01 15:15:55 2013] [error]     response = self.full_dispatch_request()
[Thu Aug 01 15:15:55 2013] [error]   File "/usr/lib/python2.6/site-packages/Flask-0.10.1-py2.6.egg/flask/app.py", line 1477, in full_dispatch_request
[Thu Aug 01 15:15:55 2013] [error]     rv = self.handle_user_exception(e)
[Thu Aug 01 15:15:55 2013] [error]   File "/usr/lib/python2.6/site-packages/Flask-0.10.1-py2.6.egg/flask/app.py", line 1381, in handle_user_exception
[Thu Aug 01 15:15:55 2013] [error]     reraise(exc_type, exc_value, tb)
[Thu Aug 01 15:15:55 2013] [error]   File "/usr/lib/python2.6/site-packages/Flask-0.10.1-py2.6.egg/flask/app.py", line 1475, in full_dispatch_request
[Thu Aug 01 15:15:55 2013] [error]     rv = self.dispatch_request()
[Thu Aug 01 15:15:55 2013] [error]   File "/usr/lib/python2.6/site-packages/Flask-0.10.1-py2.6.egg/flask/app.py", line 1461, in dispatch_request
[Thu Aug 01 15:15:55 2013] [error]     return self.view_functions[rule.endpoint](**req.view_args)
[Thu Aug 01 15:15:55 2013] [error]   File "/home/keola/obsMonitor/webInterface/server.py", line 234, in list_fits
[Thu Aug 01 15:15:55 2013] [error]     for c in fitsView["columns"]:
[Thu Aug 01 15:15:55 2013] [error] TypeError: 'NoneType' object is unsubscriptable
[Thu Aug 01 15:15:56 2013] [error] ERROR:server:Exception on /fits/51f9b2ec52ddfd690fcb73a8/51f9b2d952ddfd68f95bb489 [GET]
[Thu Aug 01 15:15:56 2013] [error] Traceback (most recent call last):
[Thu Aug 01 15:15:56 2013] [error]   File "/usr/lib/python2.6/site-packages/Flask-0.10.1-py2.6.egg/flask/app.py", line 1817, in wsgi_app
[Thu Aug 01 15:15:56 2013] [error]     response = self.full_dispatch_request()
[Thu Aug 01 15:15:56 2013] [error]   File "/usr/lib/python2.6/site-packages/Flask-0.10.1-py2.6.egg/flask/app.py", line 1477, in full_dispatch_request
[Thu Aug 01 15:15:56 2013] [error]     rv = self.handle_user_exception(e)
[Thu Aug 01 15:15:56 2013] [error]   File "/usr/lib/python2.6/site-packages/Flask-0.10.1-py2.6.egg/flask/app.py", line 1381, in handle_user_exception
[Thu Aug 01 15:15:56 2013] [error]     reraise(exc_type, exc_value, tb)
[Thu Aug 01 15:15:56 2013] [error]   File "/usr/lib/python2.6/site-packages/Flask-0.10.1-py2.6.egg/flask/app.py", line 1475, in full_dispatch_request
[Thu Aug 01 15:15:56 2013] [error]     rv = self.dispatch_request()
[Thu Aug 01 15:15:56 2013] [error]   File "/usr/lib/python2.6/site-packages/Flask-0.10.1-py2.6.egg/flask/app.py", line 1461, in dispatch_request
[Thu Aug 01 15:15:56 2013] [error]     return self.view_functions[rule.endpoint](**req.view_args)
[Thu Aug 01 15:15:56 2013] [error]   File "/home/keola/obsMonitor/webInterface/server.py", line 234, in list_fits
[Thu Aug 01 15:15:56 2013] [error]     for c in fitsView["columns"]:
[Thu Aug 01 15:15:56 2013] [error] TypeError: 'NoneType' object is unsubscriptable
[Thu Aug 01 15:15:56 2013] [error] ERROR:server:Exception on /fits/51f9b2ec52ddfd690fcb73a8/51f9b2d952ddfd68f95bb489 [GET]
[Thu Aug 01 15:15:56 2013] [error] Traceback (most recent call last):
[Thu Aug 01 15:15:56 2013] [error]   File "/usr/lib/python2.6/site-packages/Flask-0.10.1-py2.6.egg/flask/app.py", line 1817, in wsgi_app
[Thu Aug 01 15:15:56 2013] [error]     response = self.full_dispatch_request()
[Thu Aug 01 15:15:56 2013] [error]   File "/usr/lib/python2.6/site-packages/Flask-0.10.1-py2.6.egg/flask/app.py", line 1477, in full_dispatch_request
[Thu Aug 01 15:15:56 2013] [error]     rv = self.handle_user_exception(e)
[Thu Aug 01 15:15:56 2013] [error]   File "/usr/lib/python2.6/site-packages/Flask-0.10.1-py2.6.egg/flask/app.py", line 1381, in handle_user_exception
[Thu Aug 01 15:15:56 2013] [error]     reraise(exc_type, exc_value, tb)
[Thu Aug 01 15:15:56 2013] [error]   File "/usr/lib/python2.6/site-packages/Flask-0.10.1-py2.6.egg/flask/app.py", line 1475, in full_dispatch_request
[Thu Aug 01 15:15:56 2013] [error]     rv = self.dispatch_request()
[Thu Aug 01 15:15:56 2013] [error]   File "/usr/lib/python2.6/site-packages/Flask-0.10.1-py2.6.egg/flask/app.py", line 1461, in dispatch_request
[Thu Aug 01 15:15:56 2013] [error]     return self.view_functions[rule.endpoint](**req.view_args)
[Thu Aug 01 15:15:56 2013] [error]   File "/home/keola/obsMonitor/webInterface/server.py", line 234, in list_fits
[Thu Aug 01 15:15:56 2013] [error]     for c in fitsView["columns"]:
[Thu Aug 01 15:15:56 2013] [error] TypeError: 'NoneType' object is unsubscriptable
[Thu Aug 01 15:15:56 2013] [error] ERROR:server:Exception on /fits/51f9b2ec52ddfd690fcb73a8/51f9b2d952ddfd68f95bb489 [GET]
[Thu Aug 01 15:15:56 2013] [error] Traceback (most recent call last):
[Thu Aug 01 15:15:56 2013] [error]   File "/usr/lib/python2.6/site-packages/Flask-0.10.1-py2.6.egg/flask/app.py", line 1817, in wsgi_app
[Thu Aug 01 15:15:56 2013] [error]     response = self.full_dispatch_request()
[Thu Aug 01 15:15:56 2013] [error]   File "/usr/lib/python2.6/site-packages/Flask-0.10.1-py2.6.egg/flask/app.py", line 1477, in full_dispatch_request
[Thu Aug 01 15:15:56 2013] [error]     rv = self.handle_user_exception(e)
[Thu Aug 01 15:15:56 2013] [error]   File "/usr/lib/python2.6/site-packages/Flask-0.10.1-py2.6.egg/flask/app.py", line 1381, in handle_user_exception
[Thu Aug 01 15:15:56 2013] [error]     reraise(exc_type, exc_value, tb)
[Thu Aug 01 15:15:56 2013] [error]   File "/usr/lib/python2.6/site-packages/Flask-0.10.1-py2.6.egg/flask/app.py", line 1475, in full_dispatch_request
[Thu Aug 01 15:15:56 2013] [error]     rv = self.dispatch_request()
[Thu Aug 01 15:15:56 2013] [error]   File "/usr/lib/python2.6/site-packages/Flask-0.10.1-py2.6.egg/flask/app.py", line 1461, in dispatch_request
[Thu Aug 01 15:15:56 2013] [error]     return self.view_functions[rule.endpoint](**req.view_args)
[Thu Aug 01 15:15:56 2013] [error]   File "/home/keola/obsMonitor/webInterface/server.py", line 234, in list_fits
[Thu Aug 01 15:15:56 2013] [error]     for c in fitsView["columns"]:
[Thu Aug 01 15:15:56 2013] [error] TypeError: 'NoneType' object is unsubscriptable
[Thu Aug 01 15:15:56 2013] [error] ERROR:server:Exception on /fits/51f9b2ec52ddfd690fcb73a8/51f9b2d952ddfd68f95bb489 [GET]
[Thu Aug 01 15:15:56 2013] [error] Traceback (most recent call last):
[Thu Aug 01 15:15:56 2013] [error]   File "/usr/lib/python2.6/site-packages/Flask-0.10.1-py2.6.egg/flask/app.py", line 1817, in wsgi_app
[Thu Aug 01 15:15:56 2013] [error]     response = self.full_dispatch_request()
[Thu Aug 01 15:15:56 2013] [error]   File "/usr/lib/python2.6/site-packages/Flask-0.10.1-py2.6.egg/flask/app.py", line 1477, in full_dispatch_request
[Thu Aug 01 15:15:56 2013] [error]     rv = self.handle_user_exception(e)
[Thu Aug 01 15:15:56 2013] [error]   File "/usr/lib/python2.6/site-packages/Flask-0.10.1-py2.6.egg/flask/app.py", line 1381, in handle_user_exception
[Thu Aug 01 15:15:56 2013] [error]     reraise(exc_type, exc_value, tb)
[Thu Aug 01 15:15:56 2013] [error]   File "/usr/lib/python2.6/site-packages/Flask-0.10.1-py2.6.egg/flask/app.py", line 1475, in full_dispatch_request
[Thu Aug 01 15:15:56 2013] [error]     rv = self.dispatch_request()
[Thu Aug 01 15:15:56 2013] [error]   File "/usr/lib/python2.6/site-packages/Flask-0.10.1-py2.6.egg/flask/app.py", line 1461, in dispatch_request
[Thu Aug 01 15:15:56 2013] [error]     return self.view_functions[rule.endpoint](**req.view_args)
[Thu Aug 01 15:15:56 2013] [error]   File "/home/keola/obsMonitor/webInterface/server.py", line 234, in list_fits
[Thu Aug 01 15:15:56 2013] [error]     for c in fitsView["columns"]:
[Thu Aug 01 15:15:56 2013] [error] TypeError: 'NoneType' object is unsubscriptable
[Sun Aug 04 03:37:02 2013] [notice] SIGHUP received.  Attempting to restart
[Sun Aug 04 03:37:02 2013] [notice] Digest: generating secret for digest authentication ...
[Sun Aug 04 03:37:02 2013] [notice] Digest: done
[Sun Aug 04 03:37:02 2013] [notice] Apache/2.2.15 (Unix) DAV/2 PHP/5.3.3 mod_ssl/2.2.15 OpenSSL/1.0.0-fips mod_wsgi/3.2 Python/2.6.6 mod_perl/2.0.4 Perl/v5.10.1 configured -- resuming normal operations
[Sun Aug 11 03:30:01 2013] [notice] SIGHUP received.  Attempting to restart
[Sun Aug 11 03:30:02 2013] [notice] Digest: generating secret for digest authentication ...
[Sun Aug 11 03:30:02 2013] [notice] Digest: done
[Sun Aug 11 03:30:02 2013] [notice] Apache/2.2.15 (Unix) DAV/2 PHP/5.3.3 mod_ssl/2.2.15 OpenSSL/1.0.0-fips mod_wsgi/3.2 Python/2.6.6 mod_perl/2.0.4 Perl/v5.10.1 configured -- resuming normal operations
[Sun Aug 18 03:08:02 2013] [notice] SIGHUP received.  Attempting to restart
[Sun Aug 18 03:08:02 2013] [notice] Digest: generating secret for digest authentication ...
[Sun Aug 18 03:08:02 2013] [notice] Digest: done
[Sun Aug 18 03:08:02 2013] [notice] Apache/2.2.15 (Unix) DAV/2 PHP/5.3.3 mod_ssl/2.2.15 OpenSSL/1.0.0-fips mod_wsgi/3.2 Python/2.6.6 mod_perl/2.0.4 Perl/v5.10.1 configured -- resuming normal operations
[Thu Aug 22 20:57:59 2013] [notice] SELinux policy enabled; httpd running as context system_u:system_r:httpd_t:s0
[Thu Aug 22 20:57:59 2013] [notice] suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
[Thu Aug 22 20:57:59 2013] [notice] Digest: generating secret for digest authentication ...
[Thu Aug 22 20:57:59 2013] [notice] Digest: done
[Thu Aug 22 20:57:59 2013] [notice] Apache/2.2.15 (Unix) DAV/2 PHP/5.3.3 mod_ssl/2.2.15 OpenSSL/1.0.0-fips mod_wsgi/3.2 Python/2.6.6 mod_perl/2.0.4 Perl/v5.10.1 configured -- resuming normal operations
[Sun Aug 25 03:37:02 2013] [notice] SIGHUP received.  Attempting to restart
[Sun Aug 25 03:37:02 2013] [notice] Digest: generating secret for digest authentication ...
[Sun Aug 25 03:37:02 2013] [notice] Digest: done
[Sun Aug 25 03:37:02 2013] [notice] Apache/2.2.15 (Unix) DAV/2 PHP/5.3.3 mod_ssl/2.2.15 OpenSSL/1.0.0-fips mod_wsgi/3.2 Python/2.6.6 mod_perl/2.0.4 Perl/v5.10.1 configured -- resuming normal operations
[Mon Aug 26 16:07:55 2013] [notice] SELinux policy enabled; httpd running as context system_u:system_r:httpd_t:s0
[Mon Aug 26 16:07:55 2013] [notice] suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
[Mon Aug 26 16:07:55 2013] [notice] Digest: generating secret for digest authentication ...
[Mon Aug 26 16:07:55 2013] [notice] Digest: done
[Mon Aug 26 16:07:57 2013] [notice] Apache/2.2.15 (Unix) DAV/2 PHP/5.3.3 mod_ssl/2.2.15 OpenSSL/1.0.0-fips mod_wsgi/3.2 Python/2.6.6 mod_perl/2.0.4 Perl/v5.10.1 configured -- resuming normal operations
[Sat Aug 31 15:14:27 2013] [error] ERROR:server:Exception on /fits/522294b752ddfd448622cfcc [PUT]
[Sat Aug 31 15:14:27 2013] [error] Traceback (most recent call last):
[Sat Aug 31 15:14:27 2013] [error]   File "/usr/lib/python2.6/site-packages/Flask-0.10.1-py2.6.egg/flask/app.py", line 1817, in wsgi_app
[Sat Aug 31 15:14:27 2013] [error]     response = self.full_dispatch_request()
[Sat Aug 31 15:14:27 2013] [error]   File "/usr/lib/python2.6/site-packages/Flask-0.10.1-py2.6.egg/flask/app.py", line 1477, in full_dispatch_request
[Sat Aug 31 15:14:27 2013] [error]     rv = self.handle_user_exception(e)
[Sat Aug 31 15:14:27 2013] [error]   File "/usr/lib/python2.6/site-packages/Flask-0.10.1-py2.6.egg/flask/app.py", line 1381, in handle_user_exception
[Sat Aug 31 15:14:27 2013] [error]     reraise(exc_type, exc_value, tb)
[Sat Aug 31 15:14:27 2013] [error]   File "/usr/lib/python2.6/site-packages/Flask-0.10.1-py2.6.egg/flask/app.py", line 1475, in full_dispatch_request
[Sat Aug 31 15:14:27 2013] [error]     rv = self.dispatch_request()
[Sat Aug 31 15:14:27 2013] [error]   File "/usr/lib/python2.6/site-packages/Flask-0.10.1-py2.6.egg/flask/app.py", line 1461, in dispatch_request
[Sat Aug 31 15:14:27 2013] [error]     return self.view_functions[rule.endpoint](**req.view_args)
[Sat Aug 31 15:14:27 2013] [error]   File "/home/keola/obsMonitor/webInterface/server.py", line 422, in update_fits_comment
[Sat Aug 31 15:14:27 2013] [error]     fullFits["comment"] = inFits["comment"]
[Sat Aug 31 15:14:27 2013] [error] KeyError: 'comment'
[Sat Aug 31 17:22:29 2013] [error] ERROR:server:Exception on /activeLogs/5222895e52ddfd6962c9307a [GET]
[Sat Aug 31 17:22:29 2013] [error] Traceback (most recent call last):
[Sat Aug 31 17:22:29 2013] [error]   File "/usr/lib/python2.6/site-packages/Flask-0.10.1-py2.6.egg/flask/app.py", line 1817, in wsgi_app
[Sat Aug 31 17:22:29 2013] [error]     response = self.full_dispatch_request()
[Sat Aug 31 17:22:29 2013] [error]   File "/usr/lib/python2.6/site-packages/Flask-0.10.1-py2.6.egg/flask/app.py", line 1477, in full_dispatch_request
[Sat Aug 31 17:22:29 2013] [error]     rv = self.handle_user_exception(e)
[Sat Aug 31 17:22:29 2013] [error]   File "/usr/lib/python2.6/site-packages/Flask-0.10.1-py2.6.egg/flask/app.py", line 1381, in handle_user_exception
[Sat Aug 31 17:22:29 2013] [error]     reraise(exc_type, exc_value, tb)
[Sat Aug 31 17:22:29 2013] [error]   File "/usr/lib/python2.6/site-packages/Flask-0.10.1-py2.6.egg/flask/app.py", line 1475, in full_dispatch_request
[Sat Aug 31 17:22:29 2013] [error]     rv = self.dispatch_request()
[Sat Aug 31 17:22:29 2013] [error]   File "/usr/lib/python2.6/site-packages/Flask-0.10.1-py2.6.egg/flask/app.py", line 1461, in dispatch_request
[Sat Aug 31 17:22:29 2013] [error]     return self.view_functions[rule.endpoint](**req.view_args)
[Sat Aug 31 17:22:29 2013] [error]   File "/home/keola/obsMonitor/webInterface/server.py", line 117, in get_log
[Sat Aug 31 17:22:29 2013] [error]     log["datestamp"] = log["utcDate"].strftime("%Y-%m-%d (UTC)")
[Sat Aug 31 17:22:29 2013] [error] TypeError: 'NoneType' object is unsubscriptable
[Sun Sep 01 03:35:02 2013] [notice] SIGHUP received.  Attempting to restart
[Sun Sep 01 03:35:02 2013] [notice] Digest: generating secret for digest authentication ...
[Sun Sep 01 03:35:02 2013] [notice] Digest: done
[Sun Sep 01 03:35:02 2013] [notice] Apache/2.2.15 (Unix) DAV/2 PHP/5.3.3 mod_ssl/2.2.15 OpenSSL/1.0.0-fips mod_wsgi/3.2 Python/2.6.6 mod_perl/2.0.4 Perl/v5.10.1 configured -- resuming normal operations
[Sun Sep 01 05:07:20 2013] [error] ERROR:server:Exception on /print/5222895e52ddfd6962c9307f/51fb084252ddfd4051633315 [GET]
[Sun Sep 01 05:07:20 2013] [error] Traceback (most recent call last):
[Sun Sep 01 05:07:20 2013] [error]   File "/usr/lib/python2.6/site-packages/Flask-0.10.1-py2.6.egg/flask/app.py", line 1817, in wsgi_app
[Sun Sep 01 05:07:20 2013] [error]     response = self.full_dispatch_request()
[Sun Sep 01 05:07:20 2013] [error]   File "/usr/lib/python2.6/site-packages/Flask-0.10.1-py2.6.egg/flask/app.py", line 1477, in full_dispatch_request
[Sun Sep 01 05:07:20 2013] [error]     rv = self.handle_user_exception(e)
[Sun Sep 01 05:07:20 2013] [error]   File "/usr/lib/python2.6/site-packages/Flask-0.10.1-py2.6.egg/flask/app.py", line 1381, in handle_user_exception
[Sun Sep 01 05:07:20 2013] [error]     reraise(exc_type, exc_value, tb)
[Sun Sep 01 05:07:20 2013] [error]   File "/usr/lib/python2.6/site-packages/Flask-0.10.1-py2.6.egg/flask/app.py", line 1475, in full_dispatch_request
[Sun Sep 01 05:07:20 2013] [error]     rv = self.dispatch_request()
[Sun Sep 01 05:07:20 2013] [error]   File "/usr/lib/python2.6/site-packages/Flask-0.10.1-py2.6.egg/flask/app.py", line 1461, in dispatch_request
[Sun Sep 01 05:07:20 2013] [error]     return self.view_functions[rule.endpoint](**req.view_args)
[Sun Sep 01 05:07:20 2013] [error]   File "/home/keola/obsMonitor/webInterface/server.py", line 402, in print_log
[Sun Sep 01 05:07:20 2013] [error]     if expanded[ f["group"] ]:
[Sun Sep 01 05:07:20 2013] [error] KeyError: u'522297c152ddfd448622cfd7'
[Wed Sep 04 19:40:33 2013] [error] ERROR:server:Exception on /fits/5228181852ddfd448622e51b [PUT]
[Wed Sep 04 19:40:33 2013] [error] Traceback (most recent call last):
[Wed Sep 04 19:40:33 2013] [error]   File "/usr/lib/python2.6/site-packages/Flask-0.10.1-py2.6.egg/flask/app.py", line 1817, in wsgi_app
[Wed Sep 04 19:40:33 2013] [error]     response = self.full_dispatch_request()
[Wed Sep 04 19:40:33 2013] [error]   File "/usr/lib/python2.6/site-packages/Flask-0.10.1-py2.6.egg/flask/app.py", line 1477, in full_dispatch_request
[Wed Sep 04 19:40:33 2013] [error]     rv = self.handle_user_exception(e)
[Wed Sep 04 19:40:33 2013] [error]   File "/usr/lib/python2.6/site-packages/Flask-0.10.1-py2.6.egg/flask/app.py", line 1381, in handle_user_exception
[Wed Sep 04 19:40:33 2013] [error]     reraise(exc_type, exc_value, tb)
[Wed Sep 04 19:40:33 2013] [error]   File "/usr/lib/python2.6/site-packages/Flask-0.10.1-py2.6.egg/flask/app.py", line 1475, in full_dispatch_request
[Wed Sep 04 19:40:33 2013] [error]     rv = self.dispatch_request()
[Wed Sep 04 19:40:33 2013] [error]   File "/usr/lib/python2.6/site-packages/Flask-0.10.1-py2.6.egg/flask/app.py", line 1461, in dispatch_request
[Wed Sep 04 19:40:33 2013] [error]     return self.view_functions[rule.endpoint](**req.view_args)
[Wed Sep 04 19:40:33 2013] [error]   File "/home/keola/obsMonitor/webInterface/server.py", line 422, in update_fits_comment
[Wed Sep 04 19:40:33 2013] [error]     fullFits["comment"] = inFits["comment"]
[Wed Sep 04 19:40:33 2013] [error] KeyError: 'comment'
[Sun Sep 08 03:28:03 2013] [notice] SIGHUP received.  Attempting to restart
[Sun Sep 08 03:28:03 2013] [notice] Digest: generating secret for digest authentication ...
[Sun Sep 08 03:28:03 2013] [notice] Digest: done
[Sun Sep 08 03:28:03 2013] [notice] Apache/2.2.15 (Unix) DAV/2 PHP/5.3.3 mod_ssl/2.2.15 OpenSSL/1.0.0-fips mod_wsgi/3.2 Python/2.6.6 mod_perl/2.0.4 Perl/v5.10.1 configured -- resuming normal operations
[Sun Sep 15 03:41:02 2013] [notice] SIGHUP received.  Attempting to restart
[Sun Sep 15 03:41:03 2013] [notice] Digest: generating secret for digest authentication ...
[Sun Sep 15 03:41:03 2013] [notice] Digest: done
[Sun Sep 15 03:41:03 2013] [notice] Apache/2.2.15 (Unix) DAV/2 PHP/5.3.3 mod_ssl/2.2.15 OpenSSL/1.0.0-fips mod_wsgi/3.2 Python/2.6.6 mod_perl/2.0.4 Perl/v5.10.1 configured -- resuming normal operations
